# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIl5hKaKxpNe4valMTj7R2xH4W1fasR3
"""

import pandas as pd
# from pandas.tools import plotting
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

from google.colab import files
import pandas as pd

uploaded = files.upload()

from google.colab import files
import pandas as pd

uploaded = files.upload()

data_theo = pd.read_csv('/content/housepricess.csv')
data_theo.head(5)

plt.figure(figsize=(15,5))
plt.subplot(121)
data_theo['Price'].plot.hist(bins=10, title='Price')
plt.show()

col_list=['Price','SqFt']
numhouse = data_theo[data_theo.columns[data_theo.columns.isin(col_list)]]
numhouse.plot.scatter(x='SqFt', y='Price')

col_list=['Price', 'Bedrooms']
numhouse = data_theo[data_theo.columns[data_theo.columns.isin(col_list)]]
plt.figure(figsize=(15,5))
numhouse.boxplot(by='Bedrooms')
plt.show()